// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client'
import { client } from './client.gen'
import type {
    GetAllTimeData,
    GetAllTimeResponses,
    GetBadgeData,
    GetBadgeResponses,
    GetHealthData,
    GetHealthResponses,
    GetHeartbeatsData,
    GetHeartbeatsErrors,
    GetHeartbeatsResponses,
    GetSummaryData,
    GetSummaryResponses,
    GetWakatimeLeadersData,
    GetWakatimeLeadersResponses,
    GetWakatimeProjectData,
    GetWakatimeProjectResponses,
    GetWakatimeProjectsData,
    GetWakatimeProjectsResponses,
    GetWakatimesTatsData,
    GetWakatimesTatsResponses,
    GetWakatimeSummariesData,
    GetWakatimeSummariesResponses,
    GetWakatimeUseragentsData,
    GetWakatimeUseragentsResponses,
    GetWakatimeUserData,
    GetWakatimeUserResponses,
    PostDiagnosticsData,
    PostDiagnosticsResponses,
    PostHeartbeat2Data,
    PostHeartbeat2Responses,
    PostHeartbeat3Data,
    PostHeartbeat3Responses,
    PostHeartbeat4Data,
    PostHeartbeat4Responses,
    PostHeartbeat5Data,
    PostHeartbeat5Responses,
    PostHeartbeat6Data,
    PostHeartbeat6Responses,
    PostHeartbeat7Data,
    PostHeartbeat7Responses,
    PostHeartbeat8Data,
    PostHeartbeat8Responses,
    PostHeartbeatData,
    PostHeartbeatResponses,
    StatusbarData,
    StatusbarResponses,
} from './types.gen'

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
    TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>
}

/**
 * Get badge data
 *
 * Retrieve total time for a given entity (e.g. a project) within a given range (e.g. one week) in a format compatible with [Shields.io](https://shields.io/endpoint). Requires public data access to be allowed.
 */
export const getBadge = <ThrowOnError extends boolean = false>(
    options: Options<GetBadgeData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetBadgeResponses, unknown, ThrowOnError>({
        url: '/compat/shields/v1/{user}/{interval}/{filter}',
        ...options,
    })

/**
 * List of users ranked by coding activity in descending order.
 *
 * Mimics https://wakatime.com/developers#leaders
 */
export const getWakatimeLeaders = <ThrowOnError extends boolean = false>(
    options?: Options<GetWakatimeLeadersData, ThrowOnError>,
) =>
    (options?.client ?? client).get<GetWakatimeLeadersResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/leaders',
        ...options,
    })

/**
 * Retrieve the given user
 *
 * Mimics https://wakatime.com/developers#users
 */
export const getWakatimeUser = <ThrowOnError extends boolean = false>(
    options: Options<GetWakatimeUserData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetWakatimeUserResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}',
        ...options,
    })

/**
 * Retrieve summary for all time
 *
 * Mimics https://wakatime.com/developers#all_time_since_today
 */
export const getAllTime = <ThrowOnError extends boolean = false>(
    options: Options<GetAllTimeData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetAllTimeResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/all_time_since_today',
        ...options,
    })

/**
 * Get heartbeats of user for specified date
 */
export const getHeartbeats = <ThrowOnError extends boolean = false>(
    options: Options<GetHeartbeatsData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetHeartbeatsResponses, GetHeartbeatsErrors, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/heartbeats',
        ...options,
    })

/**
 * Push a new heartbeat
 */
export const postHeartbeat3 = <ThrowOnError extends boolean = false>(
    options: Options<PostHeartbeat3Data, ThrowOnError>,
) =>
    (options.client ?? client).post<PostHeartbeat3Responses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/heartbeats',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Push new heartbeats
 */
export const postHeartbeat7 = <ThrowOnError extends boolean = false>(
    options: Options<PostHeartbeat7Data, ThrowOnError>,
) =>
    (options.client ?? client).post<PostHeartbeat7Responses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/heartbeats.bulk',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Retrieve and filter the user's projects
 *
 * Mimics https://wakatime.com/developers#projects
 */
export const getWakatimeProjects = <ThrowOnError extends boolean = false>(
    options: Options<GetWakatimeProjectsData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetWakatimeProjectsResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/projects',
        ...options,
    })

/**
 * Retrieve a single project
 *
 * Mimics undocumented endpoint related to https://wakatime.com/developers#projects
 */
export const getWakatimeProject = <ThrowOnError extends boolean = false>(
    options: Options<GetWakatimeProjectData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetWakatimeProjectResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/projects/{id}',
        ...options,
    })

/**
 * Retrieve statistics for a given user
 *
 * Mimics https://wakatime.com/developers#stats
 */
export const getWakatimesTats = <ThrowOnError extends boolean = false>(
    options: Options<GetWakatimesTatsData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetWakatimesTatsResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/stats/{range}',
        ...options,
    })

/**
 * Retrieve WakaTime-compatible summaries
 *
 * Mimics https://wakatime.com/developers#summaries.
 */
export const getWakatimeSummaries = <ThrowOnError extends boolean = false>(
    options: Options<GetWakatimeSummariesData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetWakatimeSummariesResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/summaries',
        ...options,
    })

/**
 * List of unique user agents for given user.
 *
 * Mimics https://wakatime.com/developers#user_agents
 */
export const getWakatimeUseragents = <ThrowOnError extends boolean = false>(
    options: Options<GetWakatimeUseragentsData, ThrowOnError>,
) =>
    (options.client ?? client).get<GetWakatimeUseragentsResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/compat/wakatime/v1/users/{user}/user_agents',
        ...options,
    })

/**
 * Check the application's health status
 */
export const getHealth = <ThrowOnError extends boolean = false>(
    options?: Options<GetHealthData, ThrowOnError>,
) =>
    (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({
        url: '/health',
        ...options,
    })

/**
 * Push a new heartbeat
 */
export const postHeartbeat = <ThrowOnError extends boolean = false>(
    options: Options<PostHeartbeatData, ThrowOnError>,
) =>
    (options.client ?? client).post<PostHeartbeatResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/heartbeat',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Push new heartbeats
 */
export const postHeartbeat5 = <ThrowOnError extends boolean = false>(
    options: Options<PostHeartbeat5Data, ThrowOnError>,
) =>
    (options.client ?? client).post<PostHeartbeat5Responses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/heartbeats',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Push a new diagnostics object
 */
export const postDiagnostics = <ThrowOnError extends boolean = false>(
    options: Options<PostDiagnosticsData, ThrowOnError>,
) =>
    (options.client ?? client).post<PostDiagnosticsResponses, unknown, ThrowOnError>({
        url: '/plugins/errors',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Retrieve a summary
 */
export const getSummary = <ThrowOnError extends boolean = false>(
    options?: Options<GetSummaryData, ThrowOnError>,
) =>
    (options?.client ?? client).get<GetSummaryResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/summary',
        ...options,
    })

/**
 * Push a new heartbeat
 */
export const postHeartbeat4 = <ThrowOnError extends boolean = false>(
    options: Options<PostHeartbeat4Data, ThrowOnError>,
) =>
    (options.client ?? client).post<PostHeartbeat4Responses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/users/{user}/heartbeats',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Push new heartbeats
 */
export const postHeartbeat8 = <ThrowOnError extends boolean = false>(
    options: Options<PostHeartbeat8Data, ThrowOnError>,
) =>
    (options.client ?? client).post<PostHeartbeat8Responses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/users/{user}/heartbeats.bulk',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Retrieve summary for statusbar
 *
 * Mimics https://wakatime.com/api/v1/users/current/statusbar/today. Have no official documentation
 */
export const statusbar = <ThrowOnError extends boolean = false>(
    options: Options<StatusbarData, ThrowOnError>,
) =>
    (options.client ?? client).get<StatusbarResponses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/users/{user}/statusbar/today',
        ...options,
    })

/**
 * Push a new heartbeat
 */
export const postHeartbeat2 = <ThrowOnError extends boolean = false>(
    options: Options<PostHeartbeat2Data, ThrowOnError>,
) =>
    (options.client ?? client).post<PostHeartbeat2Responses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/v1/users/{user}/heartbeats',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })

/**
 * Push new heartbeats
 */
export const postHeartbeat6 = <ThrowOnError extends boolean = false>(
    options: Options<PostHeartbeat6Data, ThrowOnError>,
) =>
    (options.client ?? client).post<PostHeartbeat6Responses, unknown, ThrowOnError>({
        security: [{ name: 'Authorization', type: 'apiKey' }],
        url: '/v1/users/{user}/heartbeats.bulk',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers,
        },
    })
