// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://wakapi.pixlmint.ch/api' | (string & {})
}

export type ModelsDiagnostics = {
    architecture?: string
    cli_version?: string
    id?: number
    logs?: string
    platform?: string
    plugin?: string
    stacktrace?: string
}

export type ModelsHeartbeat = {
    ai_line_changes?: number
    branch?: string
    category?: string
    /**
     * https://gorm.io/docs/conventions.html#CreatedAt
     */
    created_at?: number
    cursorpos?: number
    /**
     * ignored because editor might be parsed differently by wakatime
     */
    editor?: string
    entity?: string
    human_line_changes?: number
    is_write?: boolean
    language?: string
    line_additions?: number
    line_deletions?: number
    lineno?: number
    lines?: number
    /**
     * ignored because wakatime api doesn't return machines currently
     */
    machine?: string
    /**
     * ignored because os might be parsed differently by wakatime
     */
    operating_system?: string
    project?: string
    project_root_count?: number
    /**
     * note: on sqlite, table will have an additional column `time_real`, introduced "manually" by migration 20260111
     * see https://github.com/muety/wakapi/issues/882 for details
     */
    time?: number
    type?: string
    user_agent?: string
}

export type ModelsSummary = {
    /**
     * branches are not persisted, but calculated at runtime in case a project Filter is applied
     */
    branches?: Array<ModelsSummaryItem>
    categories?: Array<ModelsSummaryItem>
    editors?: Array<ModelsSummaryItem>
    /**
     * entities are not persisted, but calculated at runtime in case a project Filter is applied
     */
    entities?: Array<ModelsSummaryItem>
    /**
     * filled by gorm if not set, see https://gorm.io/docs/conventions.html#CreatedAt
     */
    from?: string
    /**
     * labels are not persisted, but calculated at runtime, i.e. when summary is retrieved
     */
    labels?: Array<ModelsSummaryItem>
    languages?: Array<ModelsSummaryItem>
    machines?: Array<ModelsSummaryItem>
    operating_systems?: Array<ModelsSummaryItem>
    /**
     * Previously, all the following properties created a cascade foreign key constraint on the summary_items table
     * back to this summary table resulting in 5 identical foreign key constraints on the summary_items table.
     * This is not a problem for PostgreSQL, MySQL and SQLite, but for MSSQL (not supported anymore though), which complains about circular cascades on
     * update/delete between these two tables. All of these created foreign key constraints are identical, so only one constraint is enough.
     * MySQL will create a foreign key constraint for every property referencing other structs, even no constraint is specified in tags.
     * So explicitly set gorm:"-" in all other properties to avoid creating duplicate foreign key constraints
     */
    projects?: Array<ModelsSummaryItem>
    /**
     * filled by gorm if not set, see https://gorm.io/docs/conventions.html#CreatedAt
     */
    to?: string
    user_id?: string
}

export type ModelsSummaryItem = {
    key?: string
    total?: number
}

export type V1AllTimeData = {
    /**
     * true if the stats are up to date; when false, a 202 response code is returned and stats will be refreshed soon>
     */
    is_up_to_date?: boolean
    range?: V1AllTimeRange
    /**
     * total time logged since account created as human readable string>
     */
    text?: string
    /**
     * total number of seconds logged since account created
     */
    total_seconds?: number
}

export type V1AllTimeRange = {
    end?: string
    end_date?: string
    start?: string
    start_date?: string
    timezone?: string
}

export type V1AllTimeViewModel = {
    data?: V1AllTimeData
}

export type V1BadgeData = {
    color?: string
    label?: string
    message?: string
    schemaVersion?: number
}

export type V1HeartbeatEntry = {
    ai_line_changes?: number
    branch?: string
    category?: string
    created_at?: string
    cursorpos?: number
    entity?: string
    human_line_changes?: number
    id?: string
    is_write?: boolean
    language?: string
    line_additions?: number
    line_deletions?: number
    lineno?: number
    lines?: number
    machine_name_id?: string
    project?: string
    time?: number
    type?: string
    user_agent_id?: string
    user_id?: string
}

export type V1HeartbeatsResult = {
    data?: Array<V1HeartbeatEntry>
    end?: string
    start?: string
    timezone?: string
}

export type V1LeadersCurrentUser = {
    page?: number
    rank?: number
    user?: V1User
}

export type V1LeadersEntry = {
    rank?: number
    running_total?: V1LeadersRunningTotal
    user?: V1User
}

export type V1LeadersLanguage = {
    name?: string
    total_seconds?: number
}

export type V1LeadersRange = {
    end_date?: string
    end_text?: string
    name?: string
    start_date?: string
    start_text?: string
    text?: string
}

export type V1LeadersRunningTotal = {
    daily_average?: number
    human_readable_daily_average?: string
    human_readable_total?: string
    languages?: Array<V1LeadersLanguage>
    total_seconds?: number
}

export type V1LeadersViewModel = {
    current_user?: V1LeadersCurrentUser
    data?: Array<V1LeadersEntry>
    language?: string
    page?: number
    range?: V1LeadersRange
    total_pages?: number
}

export type V1Project = {
    created_at?: string
    human_readable_last_heartbeat_at?: string
    id?: string
    last_heartbeat_at?: string
    name?: string
    urlencoded_name?: string
}

export type V1ProjectViewModel = {
    data?: V1Project
}

export type V1ProjectsViewModel = {
    data?: Array<V1Project>
}

export type V1StatsData = {
    branches?: Array<V1SummariesEntry>
    categories?: Array<V1SummariesEntry>
    daily_average?: number
    days_including_holidays?: number
    editors?: Array<V1SummariesEntry>
    end?: string
    human_readable_daily_average?: string
    human_readable_range?: string
    human_readable_total?: string
    is_coding_activity_visible?: boolean
    is_other_usage_visible?: boolean
    languages?: Array<V1SummariesEntry>
    machines?: Array<V1SummariesEntry>
    operating_systems?: Array<V1SummariesEntry>
    projects?: Array<V1SummariesEntry>
    range?: string
    start?: string
    status?: string
    timezone?: string
    total_seconds?: number
    user_id?: string
    username?: string
}

export type V1StatsViewModel = {
    data?: V1StatsData
}

export type V1StatusBarViewModel = {
    cached_at?: string
    data?: V1SummariesData
}

export type V1SummariesCumulativeTotal = {
    decimal?: string
    digital?: string
    seconds?: number
    text?: string
}

export type V1SummariesDailyAverage = {
    days_including_holidays?: number
    days_minus_holidays?: number
    holidays?: number
    seconds?: number
    seconds_including_other_language?: number
    text?: string
    text_including_other_language?: string
}

export type V1SummariesData = {
    branches?: Array<V1SummariesEntry>
    categories?: Array<V1SummariesEntry>
    dependencies?: Array<V1SummariesEntry>
    editors?: Array<V1SummariesEntry>
    entities?: Array<V1SummariesEntry>
    grand_total?: V1SummariesGrandTotal
    languages?: Array<V1SummariesEntry>
    machines?: Array<V1SummariesEntry>
    operating_systems?: Array<V1SummariesEntry>
    projects?: Array<V1SummariesEntry>
    range?: V1SummariesRange
}

export type V1SummariesEntry = {
    digital?: string
    hours?: number
    minutes?: number
    name?: string
    percent?: number
    seconds?: number
    text?: string
    total_seconds?: number
}

export type V1SummariesGrandTotal = {
    digital?: string
    hours?: number
    minutes?: number
    text?: string
    total_seconds?: number
}

export type V1SummariesRange = {
    date?: string
    end?: string
    start?: string
    text?: string
    timezone?: string
}

export type V1SummariesViewModel = {
    cumulative_total?: V1SummariesCumulativeTotal
    daily_average?: V1SummariesDailyAverage
    data?: Array<V1SummariesData>
    end?: string
    start?: string
}

export type V1User = {
    created_at?: string
    display_name?: string
    email?: string
    full_name?: string
    id?: string
    is_email_confirmed?: boolean
    is_email_public?: boolean
    last_heartbeat_at?: string
    last_plugin_name?: string
    last_project?: string
    modified_at?: string
    photo?: string
    timezone?: string
    username?: string
    website?: string
}

export type V1UserAgentEntry = {
    editor?: string
    first_seen?: string
    id?: string
    /**
     * currently not implemented
     */
    is_browser_extension?: boolean
    /**
     * currently not implemented
     */
    is_desktop_app?: boolean
    last_seen?: string
    os?: string
    value?: string
    /**
     * currently not implemented
     */
    version?: string
}

export type V1UserAgentsViewModel = {
    data?: Array<V1UserAgentEntry>
    total_pages?: number
}

export type V1UserViewModel = {
    data?: V1User
}

export type GetBadgeData = {
    body?: never
    path: {
        /**
         * User ID to fetch data for
         */
        user: string
        /**
         * Interval to aggregate data for
         */
        interval:
            | 'today'
            | 'yesterday'
            | 'week'
            | 'month'
            | 'year'
            | '7_days'
            | 'last_7_days'
            | '30_days'
            | 'last_30_days'
            | '6_months'
            | 'last_6_months'
            | '12_months'
            | 'last_12_months'
            | 'last_year'
            | 'any'
            | 'all_time'
        /**
         * Filter to apply (e.g. 'project:wakapi' or 'language:Go')
         */
        filter: string
    }
    query?: never
    url: '/compat/shields/v1/{user}/{interval}/{filter}'
}

export type GetBadgeResponses = {
    /**
     * OK
     */
    200: V1BadgeData
}

export type GetBadgeResponse = GetBadgeResponses[keyof GetBadgeResponses]

export type GetWakatimeLeadersData = {
    body?: never
    path?: never
    query?: never
    url: '/compat/wakatime/v1/leaders'
}

export type GetWakatimeLeadersResponses = {
    /**
     * OK
     */
    200: V1LeadersViewModel
}

export type GetWakatimeLeadersResponse =
    GetWakatimeLeadersResponses[keyof GetWakatimeLeadersResponses]

export type GetWakatimeUserData = {
    body?: never
    path: {
        /**
         * User ID to fetch (or 'current')
         */
        user: string
    }
    query?: never
    url: '/compat/wakatime/v1/users/{user}'
}

export type GetWakatimeUserResponses = {
    /**
     * OK
     */
    200: V1UserViewModel
}

export type GetWakatimeUserResponse = GetWakatimeUserResponses[keyof GetWakatimeUserResponses]

export type GetAllTimeData = {
    body?: never
    path: {
        /**
         * User ID to fetch data for (or 'current')
         */
        user: string
    }
    query?: never
    url: '/compat/wakatime/v1/users/{user}/all_time_since_today'
}

export type GetAllTimeResponses = {
    /**
     * OK
     */
    200: V1AllTimeViewModel
}

export type GetAllTimeResponse = GetAllTimeResponses[keyof GetAllTimeResponses]

export type GetHeartbeatsData = {
    body?: never
    path: {
        /**
         * Username (or current)
         */
        user: string
    }
    query: {
        /**
         * Date
         */
        date: string
    }
    url: '/compat/wakatime/v1/users/{user}/heartbeats'
}

export type GetHeartbeatsErrors = {
    /**
     * bad date
     */
    400: string
}

export type GetHeartbeatsError = GetHeartbeatsErrors[keyof GetHeartbeatsErrors]

export type GetHeartbeatsResponses = {
    /**
     * OK
     */
    200: V1HeartbeatsResult
}

export type GetHeartbeatsResponse = GetHeartbeatsResponses[keyof GetHeartbeatsResponses]

export type PostHeartbeat3Data = {
    /**
     * A single heartbeat
     */
    body: ModelsHeartbeat
    path: {
        /**
         * Username (or current)
         */
        user: string
    }
    query?: never
    url: '/compat/wakatime/v1/users/{user}/heartbeats'
}

export type PostHeartbeat3Responses = {
    /**
     * Created
     */
    201: unknown
}

export type PostHeartbeat7Data = {
    /**
     * Multiple heartbeats
     */
    body: Array<ModelsHeartbeat>
    path: {
        /**
         * Username (or current)
         */
        user: string
    }
    query?: never
    url: '/compat/wakatime/v1/users/{user}/heartbeats.bulk'
}

export type PostHeartbeat7Responses = {
    /**
     * Created
     */
    201: unknown
}

export type GetWakatimeProjectsData = {
    body?: never
    path: {
        /**
         * User ID to fetch data for (or 'current')
         */
        user: string
    }
    query?: {
        /**
         * Query to filter projects by
         */
        q?: string
    }
    url: '/compat/wakatime/v1/users/{user}/projects'
}

export type GetWakatimeProjectsResponses = {
    /**
     * OK
     */
    200: V1ProjectsViewModel
}

export type GetWakatimeProjectsResponse =
    GetWakatimeProjectsResponses[keyof GetWakatimeProjectsResponses]

export type GetWakatimeProjectData = {
    body?: never
    path: {
        /**
         * User ID to fetch data for (or 'current')
         */
        user: string
        /**
         * Project ID to fetch
         */
        id: string
    }
    query?: never
    url: '/compat/wakatime/v1/users/{user}/projects/{id}'
}

export type GetWakatimeProjectResponses = {
    /**
     * OK
     */
    200: V1ProjectViewModel
}

export type GetWakatimeProjectResponse =
    GetWakatimeProjectResponses[keyof GetWakatimeProjectResponses]

export type GetWakatimesTatsData = {
    body?: never
    path: {
        /**
         * User ID to fetch data for (or 'current')
         */
        user: string
        /**
         * Range interval identifier
         */
        range?:
            | 'today'
            | 'yesterday'
            | 'week'
            | 'month'
            | 'year'
            | '7_days'
            | 'last_7_days'
            | '30_days'
            | 'last_30_days'
            | '6_months'
            | 'last_6_months'
            | '12_months'
            | 'last_12_months'
            | 'last_year'
            | 'any'
            | 'all_time'
    }
    query?: {
        /**
         * Project to filter by
         */
        project?: string
        /**
         * Language to filter by
         */
        language?: string
        /**
         * Editor to filter by
         */
        editor?: string
        /**
         * OS to filter by
         */
        operating_system?: string
        /**
         * Machine to filter by
         */
        machine?: string
        /**
         * Project label to filter by
         */
        label?: string
    }
    url: '/compat/wakatime/v1/users/{user}/stats/{range}'
}

export type GetWakatimesTatsResponses = {
    /**
     * OK
     */
    200: V1StatsViewModel
}

export type GetWakatimesTatsResponse = GetWakatimesTatsResponses[keyof GetWakatimesTatsResponses]

export type GetWakatimeSummariesData = {
    body?: never
    path: {
        /**
         * User ID to fetch data for (or 'current')
         */
        user: string
    }
    query?: {
        /**
         * Range interval identifier
         */
        range?:
            | 'today'
            | 'yesterday'
            | 'week'
            | 'month'
            | 'year'
            | '7_days'
            | 'last_7_days'
            | '30_days'
            | 'last_30_days'
            | '6_months'
            | 'last_6_months'
            | '12_months'
            | 'last_12_months'
            | 'last_year'
            | 'any'
            | 'all_time'
        /**
         * Start date (e.g. '2021-02-07')
         */
        start?: string
        /**
         * End date (e.g. '2021-02-08')
         */
        end?: string
        /**
         * Project to filter by
         */
        project?: string
        /**
         * Language to filter by
         */
        language?: string
        /**
         * Editor to filter by
         */
        editor?: string
        /**
         * OS to filter by
         */
        operating_system?: string
        /**
         * Machine to filter by
         */
        machine?: string
        /**
         * Project label to filter by
         */
        label?: string
    }
    url: '/compat/wakatime/v1/users/{user}/summaries'
}

export type GetWakatimeSummariesResponses = {
    /**
     * OK
     */
    200: V1SummariesViewModel
}

export type GetWakatimeSummariesResponse =
    GetWakatimeSummariesResponses[keyof GetWakatimeSummariesResponses]

export type GetWakatimeUseragentsData = {
    body?: never
    path: {
        /**
         * User ID to fetch data for (or 'current')
         */
        user: string
    }
    query?: never
    url: '/compat/wakatime/v1/users/{user}/user_agents'
}

export type GetWakatimeUseragentsResponses = {
    /**
     * OK
     */
    200: V1UserAgentsViewModel
}

export type GetWakatimeUseragentsResponse =
    GetWakatimeUseragentsResponses[keyof GetWakatimeUseragentsResponses]

export type GetHealthData = {
    body?: never
    path?: never
    query?: never
    url: '/health'
}

export type GetHealthResponses = {
    /**
     * OK
     */
    200: string
}

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses]

export type PostHeartbeatData = {
    /**
     * A single heartbeat
     */
    body: ModelsHeartbeat
    path?: never
    query?: never
    url: '/heartbeat'
}

export type PostHeartbeatResponses = {
    /**
     * Created
     */
    201: unknown
}

export type PostHeartbeat5Data = {
    /**
     * Multiple heartbeats
     */
    body: Array<ModelsHeartbeat>
    path?: never
    query?: never
    url: '/heartbeats'
}

export type PostHeartbeat5Responses = {
    /**
     * Created
     */
    201: unknown
}

export type PostDiagnosticsData = {
    /**
     * A single diagnostics object sent by WakaTime CLI
     */
    body: ModelsDiagnostics
    path?: never
    query?: never
    url: '/plugins/errors'
}

export type PostDiagnosticsResponses = {
    /**
     * Created
     */
    201: unknown
}

export type GetSummaryData = {
    body?: never
    path?: never
    query?: {
        /**
         * Interval identifier
         */
        interval?:
            | 'today'
            | 'yesterday'
            | 'week'
            | 'month'
            | 'year'
            | '7_days'
            | 'last_7_days'
            | '30_days'
            | 'last_30_days'
            | '6_months'
            | 'last_6_months'
            | '12_months'
            | 'last_12_months'
            | 'last_year'
            | 'any'
            | 'all_time'
        /**
         * Start date (e.g. '2021-02-07')
         */
        from?: string
        /**
         * End date (e.g. '2021-02-08')
         */
        to?: string
        /**
         * Whether to recompute the summary from raw heartbeat or use cache
         */
        recompute?: boolean
        /**
         * Project to filter by
         */
        project?: string
        /**
         * Language to filter by
         */
        language?: string
        /**
         * Editor to filter by
         */
        editor?: string
        /**
         * OS to filter by
         */
        operating_system?: string
        /**
         * Machine to filter by
         */
        machine?: string
        /**
         * Project label to filter by
         */
        label?: string
    }
    url: '/summary'
}

export type GetSummaryResponses = {
    /**
     * OK
     */
    200: ModelsSummary
}

export type GetSummaryResponse = GetSummaryResponses[keyof GetSummaryResponses]

export type PostHeartbeat4Data = {
    /**
     * A single heartbeat
     */
    body: ModelsHeartbeat
    path: {
        /**
         * Username (or current)
         */
        user: string
    }
    query?: never
    url: '/users/{user}/heartbeats'
}

export type PostHeartbeat4Responses = {
    /**
     * Created
     */
    201: unknown
}

export type PostHeartbeat8Data = {
    /**
     * Multiple heartbeats
     */
    body: Array<ModelsHeartbeat>
    path: {
        /**
         * Username (or current)
         */
        user: string
    }
    query?: never
    url: '/users/{user}/heartbeats.bulk'
}

export type PostHeartbeat8Responses = {
    /**
     * Created
     */
    201: unknown
}

export type StatusbarData = {
    body?: never
    path: {
        /**
         * User ID to fetch data for (or 'current')
         */
        user: string
    }
    query?: never
    url: '/users/{user}/statusbar/today'
}

export type StatusbarResponses = {
    /**
     * OK
     */
    200: V1StatusBarViewModel
}

export type StatusbarResponse = StatusbarResponses[keyof StatusbarResponses]

export type PostHeartbeat2Data = {
    /**
     * A single heartbeat
     */
    body: ModelsHeartbeat
    path: {
        /**
         * Username (or current)
         */
        user: string
    }
    query?: never
    url: '/v1/users/{user}/heartbeats'
}

export type PostHeartbeat2Responses = {
    /**
     * Created
     */
    201: unknown
}

export type PostHeartbeat6Data = {
    /**
     * Multiple heartbeats
     */
    body: Array<ModelsHeartbeat>
    path: {
        /**
         * Username (or current)
         */
        user: string
    }
    query?: never
    url: '/v1/users/{user}/heartbeats.bulk'
}

export type PostHeartbeat6Responses = {
    /**
     * Created
     */
    201: unknown
}
