/*
Test data generated by claude sonne 4.6 on 2026-06-02

Prompt used:

I’m writing tests in ts for a function that works with git commits. The functions I'm testing work on data retrieved through the gitea API. For that I need you to write some dummy data. The data should be a list of branches with this type:

```ts
export type Branch = {
    branch: string // branch name
    commits: Commit[] // list of commits present in this branch
}
``` 
  
Here is the type of a commit:
  
```ts
export type Commit = {
    author: string;
    commit: {
        author: string;
        message: string;
    };
    created: string;
    parents: {
        sha: string;
        created: string;
    }[];
    sha: string;
}
```
The dummy data should contain 3 branches (main + 2 features) and span 15 commits. All Commits that have been merged should be present in both the source branch as well as the merged branch
*/
type Commit = {
    author: string
    commit: {
        author: string
        message: string
    }
    created: string
    parents: {
        sha: string
        created: string
    }[]
    sha: string
}

type Branch = {
    branch: string
    commits: Commit[]
}

export const dummyCommits = (): Branch[] => {
    // --- Commits shared across branches ------------------------------------------

    /** C1: root commit — no parents */
    const c1: Commit = {
        author: 'alice',
        commit: { author: 'alice', message: 'chore: initial commit' },
        created: '2024-01-01T08:00:00Z',
        parents: [],
        sha: 'aaa0001',
    }

    const c2: Commit = {
        author: 'alice',
        commit: { author: 'alice', message: 'feat: add project scaffold' },
        created: '2024-01-02T09:00:00Z',
        parents: [{ sha: 'aaa0001', created: '2024-01-01T08:00:00Z' }],
        sha: 'aaa0002',
    }

    const c3: Commit = {
        author: 'bob',
        commit: { author: 'bob', message: 'feat: add config loader' },
        created: '2024-01-03T10:00:00Z',
        parents: [{ sha: 'aaa0002', created: '2024-01-02T09:00:00Z' }],
        sha: 'aaa0003',
    }

    /** C4–C6: feature/auth branch, branched off c3 */
    const c4: Commit = {
        author: 'carol',
        commit: { author: 'carol', message: 'feat(auth): add login endpoint' },
        created: '2024-01-04T11:00:00Z',
        parents: [{ sha: 'aaa0003', created: '2024-01-03T10:00:00Z' }],
        sha: 'bbb0004',
    }

    const c5: Commit = {
        author: 'carol',
        commit: { author: 'carol', message: 'feat(auth): add JWT validation' },
        created: '2024-01-05T11:30:00Z',
        parents: [{ sha: 'bbb0004', created: '2024-01-04T11:00:00Z' }],
        sha: 'bbb0005',
    }

    const c6: Commit = {
        author: 'dave',
        commit: { author: 'dave', message: 'test(auth): add login unit tests' },
        created: '2024-01-06T12:00:00Z',
        parents: [{ sha: 'bbb0005', created: '2024-01-05T11:30:00Z' }],
        sha: 'bbb0006',
    }

    /**
     * C7: merge commit — feature/auth (c6) merged into main (c3).
     * Two parents: the tip of main before the merge, and the tip of feature/auth.
     * Present in both main and feature/auth.
     */
    const c7: Commit = {
        author: 'alice',
        commit: { author: 'alice', message: "Merge branch 'feature/auth' into main" },
        created: '2024-01-07T14:00:00Z',
        parents: [
            { sha: 'aaa0003', created: '2024-01-03T10:00:00Z' }, // main tip before merge
            { sha: 'bbb0006', created: '2024-01-06T12:00:00Z' }, // feature/auth tip
        ],
        sha: 'aaa0007',
    }

    /** C8–C11: feature/dashboard branch, branched off c7 */
    const c8: Commit = {
        author: 'eve',
        commit: { author: 'eve', message: 'feat(dashboard): add metrics widget' },
        created: '2024-01-08T09:00:00Z',
        parents: [{ sha: 'aaa0007', created: '2024-01-07T14:00:00Z' }],
        sha: 'ccc0008',
    }

    const c9: Commit = {
        author: 'eve',
        commit: { author: 'eve', message: 'feat(dashboard): add chart component' },
        created: '2024-01-09T09:30:00Z',
        parents: [{ sha: 'ccc0008', created: '2024-01-08T09:00:00Z' }],
        sha: 'ccc0009',
    }

    const c10: Commit = {
        author: 'frank',
        commit: { author: 'frank', message: 'fix(dashboard): correct data aggregation' },
        created: '2024-01-10T10:00:00Z',
        parents: [{ sha: 'ccc0009', created: '2024-01-09T09:30:00Z' }],
        sha: 'ccc0010',
    }

    const c11: Commit = {
        author: 'frank',
        commit: { author: 'frank', message: 'style(dashboard): polish layout spacing' },
        created: '2024-01-11T10:30:00Z',
        parents: [{ sha: 'ccc0010', created: '2024-01-10T10:00:00Z' }],
        sha: 'ccc0011',
    }

    /**
     * C12: merge commit — feature/dashboard (c11) merged into main (c7).
     * Two parents: the tip of main before the merge, and the tip of feature/dashboard.
     * Present in both main and feature/dashboard.
     */
    const c12: Commit = {
        author: 'alice',
        commit: { author: 'alice', message: "Merge branch 'feature/dashboard' into main" },
        created: '2024-01-12T15:00:00Z',
        parents: [
            { sha: 'aaa0007', created: '2024-01-07T14:00:00Z' }, // main tip before merge
            { sha: 'ccc0011', created: '2024-01-11T10:30:00Z' }, // feature/dashboard tip
        ],
        sha: 'aaa0012',
    }

    /** C13–C15: post-merge commits on main only */
    const c13: Commit = {
        author: 'alice',
        commit: { author: 'alice', message: 'chore: bump version to 1.1.0' },
        created: '2024-01-13T08:00:00Z',
        parents: [{ sha: 'aaa0012', created: '2024-01-12T15:00:00Z' }],
        sha: 'aaa0013',
    }

    const c14: Commit = {
        author: 'bob',
        commit: { author: 'bob', message: 'docs: update README with new endpoints' },
        created: '2024-01-14T09:00:00Z',
        parents: [{ sha: 'aaa0013', created: '2024-01-13T08:00:00Z' }],
        sha: 'aaa0014',
    }

    const c15: Commit = {
        author: 'carol',
        commit: { author: 'carol', message: 'fix: patch security header defaults' },
        created: '2024-01-15T11:00:00Z',
        parents: [{ sha: 'aaa0014', created: '2024-01-14T09:00:00Z' }],
        sha: 'aaa0015',
    }

    // --- Branch definitions -------------------------------------------------------

    return [
        {
            branch: 'main',
            commits: [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15],
        },
        {
            branch: 'feature/auth',
            // Branched from c3; includes merge commit c7
            commits: [c1, c2, c3, c4, c5, c6],
        },
        {
            branch: 'feature/dashboard',
            // Branched from c7 (post-auth-merge); includes merge commit c12
            commits: [c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11],
        },
    ]
}
