on:
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Login to Container Registry
        uses: docker/login-action@v4
        with:
          registry: registry.pixlmint.ch
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

      
      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          context: .
          tags: registry.pixlmint.ch/pixlforge:latest
      - name: Trigger container update on unraid host
        env:
          UNRAID_SSH: ${{ secrets.UNRAID_SSH }}
          UNRAID_IP: ${{ vars.UNRAID_IP }}
        run: |
          mkdir -p ~/.ssh
          echo "$UNRAID_SSH" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $UNRAID_IP >> ~/.ssh/known_hosts 2>/dev/null
          ssh -t -o StrictHostKeyChecking=no root@$UNRAID_IP

